webtalk_init -webtalk_dir C:/Users/Acer/OneDrive/Desktop/ELD_2024/LAB_2/LAB_2.sim/sim_1/behav/xsim/xsim.dir/tb_counter_8bit_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug 27 14:17:41 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3da4b068-fe26-4960-9f11-67cc079bdf81" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5e40ac5c8fb04e8fbe9a358e18b46203" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 7535HS with Radeon Graphics        " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1880 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8276_KB" -context "xsim\\usage"
webtalk_transmit -clientid 75301034 -regid "" -xml C:/Users/Acer/OneDrive/Desktop/ELD_2024/LAB_2/LAB_2.sim/sim_1/behav/xsim/xsim.dir/tb_counter_8bit_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Acer/OneDrive/Desktop/ELD_2024/LAB_2/LAB_2.sim/sim_1/behav/xsim/xsim.dir/tb_counter_8bit_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Acer/OneDrive/Desktop/ELD_2024/LAB_2/LAB_2.sim/sim_1/behav/xsim/xsim.dir/tb_counter_8bit_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
